// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!!
// Generated by: ApplicationException.vsl in andromda-java-cartridge.
//
package sk.qbsw.android.service.exception;


/** 
 * exception which is thrown when is thread canceled
 * 
 * @author Michal Lacko
 * @version 0.1.0
 * @since 0.3.0
 */
public class CThreadCanceledException extends java.lang.Exception
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Constructs a new instance of CThreadCanceledException
	 *
	 * @param message the throwable message.
	 */
	public CThreadCanceledException (String message)
	{
		super(message);
	}

}
