package sk.qbsw.sgwt.winnetou.client.ui.component.window;

/**
 * Default factory for generating window when no window is generated by screen window factory
 * 
 * @author Dalibor Rak
 * @version 1.0
 * @since 1.0
 *
 */
public interface IWindowFactory
{
	/**
	 * Generates new window
	 * @return
	 */
	public IWindow generateWindow ();
}
